version: "3.1"

services:
  redis:
    image: redis
    ports:
      - "6379"
    env_file:
      - volumes/env/redis.env
    volumes:
      - redis-data:/data
    networks:
      - back-tier

  django-quickstart:
    image: django-quickstart:alpine
    depends_on:
      - redis
    ports:
      - "8050"
    env_file:
      - volumes/env/redis.env
      - volumes/env/django-quickstart.env
    volumes:
      - ${PWD}/volumes/django-quickstart/log:/root/log
    command: --wait redis:6379
    networks:
      - back-tier

  nginx:
    image: nginx
    labels:
      kompose.service.type: loadbalancer
    depends_on:
      - django-quickstart
    volumes:
      - ${PWD}/config/nginx-docker.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8008:80"
    networks:
      - back-tier
      - front-tier

volumes:
  redis-data:
  mysql-data:

networks:
  back-tier:
  front-tier:
